routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@homepage')->name('home');
Route::get('img/{id}', 'PublicController@img')->name('image');
Route::get('verify', 'PublicController@verify')->name('verify');
Route::get('order/{id}', 'PublicController@order')->name('order');
Route::get('send-code', 'PublicController@send_verification')->name('send_code');
Route::get('receipt/{id}', 'PublicController@receipt')->name('receipt');

Route::post('add', 'PublicController@add_cart')->name('add');
Route::post('verify-user', 'PublicController@verify_user')->name('verify_user');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('admin');
Route::get('/img/{id}/delete', 'HomeController@deleteImage')->name('delete-img');

Route::resources([
    'settings' => 'SettingsController',
    'transaction' => 'TransactionsController',
    'products' => 'ProductsController',
    'category' => 'CategoryController',
    'users' => 'UsersController',
    'orders' => 'OrdersController',
    'cart' => 'CartController',
]);

resources/views/homepage.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="token" content="{{ csrf_token() }}">
        <title>Yuan's Kitchen Garden</title>
        <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
        <link href="{{asset('css/toastr.min.css')}}" rel="stylesheet">
        <link href="{{asset('assets/css/carousel.css')}}" rel="stylesheet">
        @yield('header')
    </head>
    <body>
        <nav class="navbar navbar-inverse" style="border-radius: 0;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">Yuan's Kitchen Garden</a>
                <ul class="nav navbar-nav">
                    <li @if(Route::current()->getName() == 'home') class="active" @endif><a href="{{ route('home') }}">Home</a></li>
                    @if (Route::has('login'))
                        @auth
                            @if(auth()->user()->role=='admin')
                            <li @if(Route::current()->getName() == 'admin') class="active" @endif><a href="{{ route('admin') }}">Admin Panel</a></li>
                            @endif
                            <li @if(Route::current()->getName() == 'orders') class="active" @endif><a href="{{ route('orders.index') }}">Orders</a></li>
                            <li id="cart-nav" @if(Route::current()->getName() == 'cart') class="active" @endif><a href="{{ route('cart.index') }}"><i class="glyphicon glyphicon-shopping-cart"></i> Cart (<span>{{auth()->user()->cart()}}</span>)</a></li>
                            
                        @else
                            <li @if(Route::current()->getName() == 'login') class="active" @endif><a href="{{ route('login') }}">Login</a></li>
                            @if (Route::has('register'))
                                <li @if(Route::current()->getName() == 'register') class="active" @endif><a href="{{ route('register') }}">Register</a></li>
                            @endif
                        @endauth
                    @endif
                    <li>
                        <a href="tel:0335310282"><i class="glyphicon glyphicon-earphone"></i> (033) 531-0282</a>
                    </li>
                    <li>
                        <a href="tel:0949888808"><i class="glyphicon glyphicon-phone"></i> 0949888808</a>
                    </li>
                </ul>
                @auth
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ route('settings.index') }}">
                            {{ __('Settings') }}
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>
                    </li>
                </ul>
                @endauth
            </div>
        </nav>
        
        @yield('content')

        <script src="{{asset('js/jquery-3.4.1.min.js')}}"></script>
        <script src="{{asset('js/bootstrap.min.js')}}"></script>
        <script src="{{asset('js/toastr.min.js')}}"></script>
        <script src="{{asset('js/scripts.js')}}"></script>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
        @yield('footer')
        @if(session('success'))
            <script>toastr.success('{{ session('success') }}', 'Success!')</script>
        @endif
        @if(session('error'))
            <script>toastr.error('{{ session('error') }}', 'Error!')</script>
        @endif
    </body>
</html>

resources/views/mail.blade.php
<h2>Hi, {{ $name }}</h2>
<br>
<p>Your verication code is: </p>
<h2>{{ $code }}</h2>
<a href="{{ asset('/verify?code='.$code) }}">Click here to verify your account.</a>
<br>
<p>- Yuan's</p>